#!/usr/bin/env node
/* Writes an index.html into Notes/, Product/ and Archive/ so the landing page's
   folder links work on static hosting (GitHub Pages cannot list a directory).

   Lists the files Pages will publish: tracked ones and new ones not yet committed,
   never gitignored ones.
   Markdown opens in read.html; HTML opens directly; anything else is listed, not linked.

   Run from the repo root after adding or renaming a document:
     node tools/build-indexes.mjs            write the three index pages
     node tools/build-indexes.mjs --check    exit 1 if any page is out of date */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FOLDERS = {
  Notes: 'Grills, audits and reviews, dated. Written at the time and not kept up after, so read them as history.',
  Product: 'What we are building: the proposal, the PRDs, the copy rules, the briefs and the design system.',
  Archive: 'Superseded builds, the sketches that decided them, and a backup. Nothing live depends on this folder.'
};

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

function tracked(folder) {
  /* Tracked files plus new ones not yet committed (but not ignored ones), and only
     those still on disk, so a deleted-but-staged file cannot crash the title read. */
  const out = execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard', '--', folder], { cwd: ROOT, encoding: 'utf8' });
  return [...new Set(out.split('\0').filter(Boolean))].filter((p) => existsSync(join(ROOT, p)));
}

function titleOf(path) {
  const text = readFileSync(join(ROOT, path), 'utf8').slice(0, 4000);
  if (path.endsWith('.md')) {
    const m = text.match(/^#\s+(.+)$/m);
    return m ? m[1].replace(/[*_`]/g, '').trim() : null;
  }
  if (path.endsWith('.html')) {
    const m = text.match(/<title>([^<]*)<\/title>/i);
    return m ? m[1].replace(/&amp;/g, '&').trim() : null;
  }
  return null;
}

function item(path, folder) {
  const rel = path.slice(folder.length + 1);
  const name = rel.split('/').pop();
  const title = titleOf(path) || name;
  if (path.endsWith('.md')) {
    return `<li><a href="../read.html?f=${esc(path)}">${esc(title)}<em>${esc(rel)}</em></a></li>`;
  }
  if (path.endsWith('.html')) {
    return `<li><a href="${esc(rel)}">${esc(title)}<em>${esc(rel)}</em></a></li>`;
  }
  return `<li><span class="plain">${esc(name)}<em>${esc(rel)} · data, not a page</em></span></li>`;
}

function page(folder) {
  const files = tracked(folder).filter((p) => p !== `${folder}/index.html`);
  /* Group by the first sub-folder. A sub-folder with its own index.html is one link. */
  const top = [];
  const groups = new Map();
  for (const p of files) {
    const rest = p.slice(folder.length + 1).split('/');
    if (rest.length === 1) { top.push(p); continue; }
    const sub = rest[0];
    if (!groups.has(sub)) groups.set(sub, []);
    groups.get(sub).push(p);
  }

  const shown = (list) => list
    .filter((p) => /\.(md|html)$/.test(p) || !/\.(js|css|mjs|json|png|jpg|svg|woff2?)$/.test(p))
    .sort()
    .map((p) => item(p, folder))
    .join('\n    ');

  let body = '';
  if (top.length) body += `<ul class="files">\n    ${shown(top)}\n  </ul>\n`;
  for (const [sub, list] of [...groups].sort()) {
    const idx = `${folder}/${sub}/index.html`;
    if (list.includes(idx)) {
      const t = titleOf(idx) || sub;
      body += `  <h2 class="group">${esc(sub)}</h2>\n  <ul class="files">\n    <li><a href="${esc(sub)}/index.html">${esc(t)}<em>${esc(sub)}/</em></a></li>\n  </ul>\n`;
      continue;
    }
    const rows = shown(list);
    if (!rows) continue;
    body += `  <h2 class="group">${esc(sub)}</h2>\n  <ul class="files">\n    ${rows}\n  </ul>\n`;
  }

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(folder)} · Warhol</title>
<link rel="stylesheet" href="../site.css">
</head>
<body>
<div class="wrap">
  <nav class="crumbs" aria-label="Where you are"><a href="../index.html">Warhol</a><span aria-hidden="true">/</span><span aria-current="page">${esc(folder)}</span></nav>
  <h1 class="page">${esc(folder)}</h1>
  <p class="lede">${esc(FOLDERS[folder])}</p>
  ${body.trim()}
</div>
</body>
</html>
<!-- Generated by tools/build-indexes.mjs. Edit the script, not this file. -->
`;
}

const check = process.argv.includes('--check');
let stale = 0;
for (const folder of Object.keys(FOLDERS)) {
  const out = join(ROOT, folder, 'index.html');
  const html = page(folder);
  const before = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (before === html) continue;
  if (check) { console.log(`out of date: ${folder}/index.html`); stale += 1; continue; }
  writeFileSync(out, html);
  console.log(`wrote ${folder}/index.html`);
}
if (check && stale) process.exit(1);
